#!/usr/bin/env python3
"""Regenerate src/lib/blur-data.ts after adding/replacing images in public/images."""
import base64, subprocess, os, glob
out = ['// AUTO-GENERATED by scripts/gen-blur.py — rerun after changing images.',
       '// Tiny base64 previews for placeholder="blur" on photographic images.',
       'export const BLUR: Record<string, string> = {']
for f in sorted(glob.glob('public/images/*.webp')):
    name = '/images/' + os.path.basename(f)
    tmp = '/tmp/blur-tmp.jpg'
    subprocess.run(['sips','-s','format','jpeg','-s','formatOptions','40','--resampleWidth','24',f,'--out',tmp],
                   capture_output=True)
    b64 = base64.b64encode(open(tmp,'rb').read()).decode()
    out.append(f'  "{name}": "data:image/jpeg;base64,{b64}",')
out.append('};')
open('src/lib/blur-data.ts','w').write('\n'.join(out)+'\n')
print("done")
